pipeline {
    agent any 
    stages {
        stage('Non-parallel stage') {
            steps {
                echo 'This will execute first' 
            }
        }
        stage('Parallel') {
            steps {
                echo 'Phase' 
            }
        }
        stage('Static Analysis') {
            steps {
                echo 'Hello Everyone' 
            }
        }
        stage('Compile') {
            steps {
                echo 'This is Devops' 
            }
        }
        stage('Security Check') {
            steps {
                echo 'Run the security check against the application' 
                echo 'Added an extra echo'
            }
        }
        stage('Run Unit Tests') {
            steps {
                echo 'Welcome' 
            }
        }
        stage('Run Integration Tests') {
            steps {
                echo 'Run only crucial integration tests from the source code' 
            }
        }
        stage('Publish Artifacts') {
            steps {
                echo 'Thank You' 
            }
        }
    }
}
